= Privacy policy

This policy describes how MadiDevs (“MadiDevs”, "ShopAware", “we”, “us”) collects, receives, processes, uses, discloses, or shares your information. When you use our product or service.

MadiDevs built the ShopAware app as a free app. This app is provided by MadiDevs at no cost and is intended for use as is.

This page is used to inform users of ShopAware regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.

If you choose to use our Service, then you agree to the collection and use of information in relation with this policy. The Personal Information that we collect are used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.

The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible in the ShopAware app, unless otherwise defined in this Privacy Policy.

== Information collection and use
Information entered into ShopAware is stored on the device used to do so.

We are not collecting or saving any information entered by the user.

== Third parties
The app does not use third party services.

== Log data
We are not collecting any Log Data or any other information from the app.

== Security
User input is saved locally on the device. Data is not stored in an encrypted format. Remember that some software may be able to read saved data and collect them.

== Link to other sites
This Service may contain links to other sites. These links are always created by the user. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us.
Therefore, I strongly advise you to review the Privacy Policy of these websites. I have no control over, and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

== Changes to this privacy policy
We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page.

== Contact Us
If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.

MadiDevs

shopaware.info@gmail.com

This policy was last updated on: 20th March, 2023
